### ISSUE TITLE
민지님 만들고 싶은 스크린을 적어주세요

### ISSUE THREAD

**Issue by heyman333** [heyman333/deprocheck-rn#1]
민지님!
이번 프로젝트를 통해서 리액트와 리액트네이티브에 대해서 재미를 느끼셨으면 좋곘어요 🎉
회사에서 만드는것도 아니고 재미로 만드는 앱이니 너무 부담갖지 마시고 하고싶은대로 마음대로 코딩하시고 `PR` 날려주세요~~👍👍👍
같이 재밌게 코드리뷰 하고 꼭 출첵앱 릴리즈해엽🙃

제플린 url : zpl://project?pid=5ccd6b5dfb9c6f349c9626ce

**Comment by KKonzi** [comment]
저는 사용자 페이지 위주로 우선 해보도록 하겠습니다 😃
사실 지도 사용하는 부분에서 십만년걸릴수도 있어요....ㅎㅎㅎㅎㅎ(도망)

**Comment by heyman333** [comment]
@KKonzi 네 그럼 저는 로그인 화면과 admin쪽 진행 하겠습니다~~~
지도는 https://github.com/react-native-community/react-native-maps 를 쓸거같고,
시간은 충분하니 천천히 하셔도 됩니다~~~🤥
